title: Chris Marotta
description: My Personal Blog
author: Chris Marotta
logo: http://chrismarotta.me/static/img/ubuntu32x32.png
github: https://github.com/TheRealChrisM
about: Cybersecurity Novice

baseurl: ""
url: "http://chrismarotta.me/"

allowsearch: true

disqus_shortname: 
google_analytics: UA-101957444-1

share:
  twitter_username: \#
  fb_appid: 000000000000

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
