title: Chris Marotta
description: My Personal Blog
author: Chris Marotta
logo: https://avatars0.githubusercontent.com/u/20587220?v=3&s=460
github: https://github.com/TheRealChrisM
about: Cybersecurity Novice

baseurl: ""
url: "https://codeasashu.github.io/hcz-jekyll-blog"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: /therealchrism_
  fb_appid: 1622482361127293


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
